### PR TITLE
cargo update

### PR DESCRIPTION
**Pull request by h-michael**

### CODE REVIEW

**Comment by h-michael** [comment]
@nrc Would you bump up this after merging this?
I want update all dependencies related rls.
I'll update dependencies in the order of `rls-span`, `rls-data`, `rls-analysis`, `rls`.

**Comment by nrc** [comment]
Thanks, and sure, I'll try and pubish the new versions tomorrow.

**Comment by h-michael** [comment]
@nrc Thanks for your time. I know you're busy.

**Comment by nrc** [comment]
Published 0.4.1, sorry it took a while.

**Pull request merged**
